[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Artificial Intelligence and Personal Finance: The Role of Intelligent Technologies in Helping People Manage Their Money"
